const ISLANDS_DATA = [
    {
        id: "pollinators",
        name: "Vallée des Nectarivores",
        modelFile: "warm-island.glb",
        scale: 0.2,
        ecosystem: "Prairie tempérée méliphage",
        environmentDesc: "Une zone ouverte caractérisée par une diversité florale élevée. Ce milieu est essentiel pour le cycle de vie des angiospermes et subit de fortes pressions dues à l'agriculture intensive.",
        position: { x: -20, y: 0, z: 5 },
        color: "#ffeb3b",
        status: "unexplored",
        insects: [
            {
                id: "bee",
                name: "Abeille Mellifère",
                scientific: "Apis mellifera",
                modelFile: "bee.glb",
                modelScale: 0.9,
                taxonomy: "Ordre : Hymenoptera | Famille : Apidae",
                position: { x: 2, y: 1, z: 2 },
                icon: "🐝",
                role: "Agent de pollinisation biotique",
                habitat: "Ruches sociales et cavités naturelles",
                anecdote: "Leur système de communication par 'danse frétillante' permet de transmettre la position exacte d'une source de nectar par rapport au soleil.",
                status: "Espèce sentinelle - Vulnérable"
            },
            {
                id: "butterfly",
                name: "Grand Monarque",
                scientific: "Danaus plexippus",
                modelFile: "monarque.glb",
                modelScale: 0.08,
                taxonomy: "Ordre : Lepidoptera | Famille : Nymphalidae",
                position: { x: 32.14, y: 13.03, z: -8.28 },
                icon: "🦋",
                role: "Bio-indicateur de connectivité écologique",
                habitat: "Champs d'asclépiades et zones de migration",
                anecdote: "Ce lépidoptère parcourt jusqu'à 4 000 km lors de sa migration annuelle. Ses chenilles accumulent des toxines pour devenir immangeables.",
                status: "En danger (Liste rouge UICN)"
            },
            {
                id: "purple_butterfly",
                name: "Grand Mars Changeant",
                scientific: "Apatura iris",
                modelFile: "purple_butterfly.glb",
                modelScale: 9,
                taxonomy: "Ordre : Lepidoptera | Famille : Nymphalidae",
                position: { x: 16.54, y: 15.72, z: -0.05 },
                icon: "🦋",
                role: "Indicateur de canopée saine",
                habitat: "Lisières de forêts et saules",
                anecdote: "Ses ailes ont des reflets violets spectaculaires (iridescence) qui ne sont visibles que sous un certain angle pour attirer les femelles.",
                status: "Préoccupation mineure"
            },
            {
                id: "colibri_1",
                name: "Colibri d'Elena",
                scientific: "Mellisuga helenae",
                modelFile: "colibri.glb",
                modelScale: 0.1,
                taxonomy: "Ordre : Apodiformes | Famille : Trochilidae",
                position: { x: 31.74, y: 28.80, z: -22.09 },
                icon: "🐦",
                role: "Pollinisateur vertébré",
                habitat: "Zones riches en fleurs tubulaires",
                anecdote: "Bien que ce ne soit pas un insecte, c'est le plus petit oiseau au monde. Il bat des ailes 80 fois par seconde !",
                status: "Quasi menacé"
            }
        ],
    },
    {
        id: "forest_green",
        name: "Forêt des Coléoptères",
        modelFile: "forest-island.glb",
        scale: 1.5,
        ecosystem: "Forêt primaire à canopée dense",
        environmentDesc: "Un écosystème complexe dominé par les feuillus séculaires. L'humidité y est constante, favorisant la dégradation du bois mort, pilier de la biodiversité entomologique.",
        position: { x: 20, y: -2.2, z: -15 },
        modelOffset: -60,
        waterLevel: 0,
        color: "#4caf50",
        status: "unexplored",
        insects: [
            {
                id: "beetle_stag",
                name: "Lucane Cerf-Volant",
                scientific: "Lucanus cervus",
                modelFile: "beetle.glb",
                modelScale: 0.1,
                taxonomy: "Ordre : Coleoptera | Famille : Lucanidae",
                position: { x: -1.26, y: 0.85, z: 2.56 },
                icon: "🪲",
                role: "Ingénieur forestier saproxylophage",
                habitat: "Vieux chênes et souches en décomposition",
                anecdote: "Ses mandibules évoquant des bois de cerf ne servent qu'aux joutes entre mâles. Les larves vivent 5 ans dans le bois mort.",
                status: "Protégé (Directive Habitats)"
            },
            // NOUVEAU
            {
                id: "mantis",
                name: "Mante Religieuse",
                scientific: "Mantis religiosa",
                modelFile: "mantis.glb",
                modelScale: 10,
                taxonomy: "Ordre : Mantodea | Famille : Mantidae",
                position: { x: -0.10, y: 1.25, z: 3.04 },
                icon: "🦗",
                role: "Régulateur de populations d'insectes",
                habitat: "Hautes herbes et arbustes ensoleillés",
                anecdote: "Ses pattes avant sont des armes redoutables qui se déplient en un éclair pour capturer ses proies. Elle peut tourner la tête à 180°.",
                status: "Préoccupation mineure"
            },
            // NOUVEAU
            {
                id: "spider",
                name: "Épeire Diadème",
                scientific: "Araneus diadematus",
                modelFile: "spider.glb",
                modelScale: 0.01,
                taxonomy: "Ordre : Araneae | Famille : Araneidae",
                position: { x: -1.44, y: 0.84, z: 3.83 },
                icon: "🕷️",
                role: "Prédateur généraliste",
                habitat: "Jardins et sous-bois",
                anecdote: "Elle recycle sa toile chaque nuit en la mangeant pour récupérer les protéines avant d'en tisser une nouvelle au matin.",
                status: "Commune"
            }
        ],
    },
    {
        id: "floating_forest",
        name: "Archipel des Cimes",
        modelFile: "floating-island.glb",
        scale: 2,
        ecosystem: "Forêt d'altitude subalpine",
        environmentDesc: "Milieu caractérisé par une raréfaction de l'oxygène et des vents violents. La végétation est naine et les insectes y ont développé des stratégies de résistance thermique.",
        position: { x: 35, y: -7.5, z: 50 },
        hitboxOffset: 5,
        hitboxScale: 3,
        modelOffset: -5,
        waterLevel: 215,
        color: "#e8f1e8",
        status: "unexplored",
        insects: [
            {
                id: "ladybug",
                name: "Coccinelle à sept points",
                scientific: "Coccinella septempunctata",
                modelFile: "coccinelle.glb",
                modelScale: 5,
                taxonomy: "Ordre : Coleoptera | Famille : Coccinellidae",
                position: { x: -6.40, y: 11.91, z: -2.52 },
                icon: "🐞",
                role: "Auxiliaire de lutte biologique",
                habitat: "Végétation herbacée",
                anecdote: "Elle peut consommer 50 pucerons par jour. Sa couleur rouge vive (aposématisme) avertit les prédateurs de sa toxicité.",
                status: "Préoccupation mineure"
            },
            {
                id: "grasshopper_1",
                name: "Grande Sauterelle Verte",
                scientific: "Tettigonia viridissima",
                modelFile: "grasshopper.glb",
                modelScale: 1.5,
                taxonomy: "Ordre : Orthoptera | Famille : Tettigoniidae",
                position: { x: 4.95, y: 8.15, z: -6.94 },
                icon: "🦗",
                role: "Omnivore opportuniste",
                habitat: "Strates herbacées et arbustives",
                anecdote: "Ses antennes sont plus longues que son corps. Elle chante en frottant ses élytres (stridulation) pour attirer les femelles.",
                status: "Préoccupation mineure"
            },
            {
                id: "wasp",
                name: "Guêpe Commune",
                scientific: "Vespula vulgaris",
                modelFile: "wasp.glb",
                modelScale: 0.1,
                taxonomy: "Ordre : Hymenoptera | Famille : Vespidae",
                position: { x: 4.92, y: 8.15, z: -5.60 },
                icon: "🐝",
                role: "Régulateur et nettoyeur",
                habitat: "Nids en papier mâché (cellulose)",
                anecdote: "Contrairement à l'abeille, elle ne meurt pas après avoir piqué car son dard est lisse. C'est une architecte hors pair.",
                status: "Non menacée"
            }
        ],
    },
    {
        id: "winter",
        name: "Toundra des Neiges",
        modelFile: "winter-island.glb",
        scale: 1,
        ecosystem: "Écotone boréal arctique",
        environmentDesc: "Un désert froid où le sol reste gelé en profondeur (permafrost). La faune entomologique y est restreinte à quelques espèces possédant des molécules antigel.",
        position: { x: 25, y: -1.5, z: 2 },
        modelOffset: -40,
        waterLevel: 0,
        color: "#e8f1e8",
        status: "unexplored",
        insects: [
            {
                id: "winter_moth",
                name: "Arpenteuse hivernale",
                scientific: "Operophtera brumata",
                modelFile: "lil-moth.glb",
                modelScale: 1.5,
                taxonomy: "Ordre : Lepidoptera | Famille : Geometridae",
                position: { x: 0.45, y: 150, z: -2.62 },
                icon: "❄️",
                role: "Maillon trophique boréal",
                habitat: "Forêts de feuillus résistantes",
                anecdote: "Capable de rester active par des températures négatives grâce à des protéines antigel dans son hémolymphe.",
                status: "Sous surveillance climatique"
            }
        ],
    },
    {
        id: "decomposers",
        name: "Sanctuaire des Recycleurs",
        modelFile: "small-island.glb",
        scale: 0.01,
        ecosystem: "Humus et litière forestière",
        environmentDesc: "Le laboratoire de recyclage de la nature. Ici, les détritivores transforment la matière organique morte en nutriments minéraux assimilables par les plantes.",
        position: { x: 5, y: 0, z: -30 },
        color: "#8d6e63",
        status: "unexplored",
        insects: [
            {
                id: "woodlouse",
                name: "Cloporte Commun",
                scientific: "Armadillidium vulgare",
                modelFile: "cloporte.glb",
                modelScale: 0.2,
                taxonomy: "Ordre : Isopoda | Famille : Armadillidiidae",
                position: { x: 84.68, y: 364.74, z: -326.14 },
                icon: "🍂",
                role: "Décomposeur de cellulose",
                habitat: "Sous les pierres et bois humide",
                anecdote: "C'est un crustacé terrestre ! Il possède des branchies et doit rester en milieu humide pour respirer.",
                status: "Indispensable au cycle du carbone"
            },
            // NOUVEAU
            {
                id: "ant",
                name: "Fourmi Rousse",
                scientific: "Formica rufa",
                modelFile: "ant.glb",
                modelScale: 0.15,
                taxonomy: "Ordre : Hymenoptera | Famille : Formicidae",
                position: { x: -357.73, y: 366.32, z: 82.78 },
                icon: "🐜",
                role: "Ingénieur des écosystèmes",
                habitat: "Dômes d'aiguilles de pin",
                anecdote: "Elle projette de l'acide formique pour se défendre. Une colonie peut consommer des millions d'insectes par an.",
                status: "Protégée dans certains pays"
            }
        ],
    },
    {
        id: "aquatic",
        name: "Lagon des Odonates",
        modelFile: "phare-island.glb",
        scale: 0.5,
        ecosystem: "Zone humide lentique",
        environmentDesc: "Milieu aquatique à renouvellement lent. Les zones humides filtrent l'eau et abritent des espèces au cycle de vie double (larve aquatique / adulte aérien).",
        position: { x: -15, y: 0, z: -25 },
        color: "#29b6f6",
        status: "unexplored",
        insects: [
            {
                id: "dragonfly",
                name: "Anax Empereur",
                scientific: "Anax imperator",
                modelFile: "dragonfly.glb",
                modelScale: 1.5,
                taxonomy: "Ordre : Odonata | Famille : Aeshnidae",
                position: { x: 0, y: 2, z: 0 },
                icon: "🦟",
                role: "Super-prédateur aérien",
                habitat: "Eaux stagnantes végétalisées",
                anecdote: "Possède une vision à 360° et peut chasser en vol stationnaire ou en marche arrière.",
                status: "Bio-indicateur de qualité d'eau"
            },
            {
                id: "grasshopper_2",
                name: "Criquet des Roseaux",
                scientific: "Mecostethus parapleurus",
                modelFile: "grasshopper.glb",
                modelScale: 1.5,
                taxonomy: "Ordre : Orthoptera | Famille : Acrididae",
                position: { x: 2.55, y: 4.18, z: 9.65 },
                icon: "🦗",
                role: "Herbivore des zones humides",
                habitat: "Prairies inondables et roselières",
                anecdote: "Contrairement à la sauterelle, le criquet a des antennes courtes. Il aime l'humidité des bords de l'eau.",
                status: "Vulnérable"
            }
        ],
    },
    {
        id: "extinct",
        name: "Pic des Hautes-Alpes",
        modelFile: "mountain-island.glb",
        scale: 0.7,
        ecosystem: "Pelouses alpines rocailleuses",
        environmentDesc: "Prairies d'altitude au-dessus de la limite des arbres. Les cycles de reproduction y sont très courts à cause de la brièveté de la saison estivale.",
        position: { x: 10, y: 0, z: 5 },
        color: "#78909c",
        status: "unexplored",
        insects: [
            {
                id: "apollo",
                name: "Apollon des Montagnes",
                scientific: "Parnassius apollo",
                modelFile: "apollon.glb",
                modelScale: 0.5,
                taxonomy: "Ordre : Lepidoptera | Famille : Papilionidae",
                position: { x: 0, y: 1, z: 1 },
                icon: "🦋",
                role: "Relique glaciaire",
                habitat: "Versants ensoleillés riches en sédums",
                anecdote: "Ses ailes parsemées d'ocelles rouges effrayent les oiseaux. C'est l'un des premiers insectes protégés au monde.",
                status: "Rare - Strictement protégé"
            }
        ],
    },
    {
        id: "flower",
        name: "Atoll Florissant",
        modelFile: "flower-island.glb",
        scale: 4.5,
        ecosystem: "Jardin botanique insulaire",
        environmentDesc: "Micro-climat favorisant une floraison continue. Ce milieu sert de refuge aux insectes généralistes dans un paysage souvent fragmenté.",
        position: { x: 0, y: 0, z: 25 },
        modelOffset: -8,
        waterLevel: 0,
        color: "#bd546f",
        status: "unexplored",
        insects: [
            {
                id: "hoverfly",
                name: "Syrphe Ceinturé",
                scientific: "Episyrphus balteatus",
                modelFile: "syrphe.glb",
                modelScale: 0.3,
                taxonomy: "Ordre : Diptera | Famille : Syrphidae",
                position: { x: 0, y: 1, z: 1 },
                icon: "🐝",
                role: "Mime batesien et pollinisateur",
                habitat: "Zones fleuries diversifiées",
                anecdote: "Mime une guêpe pour effrayer les prédateurs mais n'a pas de dard. Ses larves dévorent les pucerons.",
                status: "Auxiliaire précieux"
            },
            {
                id: "colibri_2",
                name: "Colibri Rubis",
                scientific: "Archilochus colubris",
                modelFile: "colibri2.glb",
                modelScale: 12,
                taxonomy: "Ordre : Apodiformes | Famille : Trochilidae",
                position: { x: -1.33, y: 0.92, z: -0.06 },
                icon: "🐦",
                role: "Pollinisateur spécialisé",
                habitat: "Jardins et lisières",
                anecdote: "Il est capable de se souvenir de chaque fleur visitée pour ne pas y retourner tant que le nectar ne s'est pas renouvelé.",
                status: "Préoccupation mineure"
            }
        ],
    },
];

const SCIENTIFIC_QUOTES = [
    "Saviez-vous ? Les libellules existent depuis plus de 300 millions d'années.",
    "L'abeille est le seul insecte au monde qui produit de la nourriture consommée par l'homme.",
    "Un scarabée peut porter jusqu'à 850 fois son propre poids !",
    "La métamorphose transforme totalement l'anatomie d'un insecte.",
    "Certains papillons parcourent des milliers de kilomètres pour migrer."
];

const JOURNAL_STATE = {
    discoveredInsects: [],
    exploredIslands: [],
};